services:
  - type: web
    name: ai-meeting-summarizer
    env: node
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: "--max-old-space-size=512"
      - key: NPM_CONFIG_CACHE
        value: "/tmp/.npm"
      - key: CI
        value: "false"
      - key: GENERATE_SOURCEMAP
        value: "false"
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: GEMINI_API_KEY
        sync: false